### ISSUE TITLE
Error on SVR cross-validation using tune

### ISSUE THREAD

**Issue by ericoffn** [UnixJunkie/orsvm-e1071#14]
Hi there,

I am using the function tune to fit a support vector regression using a cross-validation. The independent variable is a sparse document-term matrix and I am trying to fit them on stock market and bond market returns.

When I run the cross-validation:

tune(svm, train_data, labels,
                   ranges = list(epsilon = seq(0,1,0.1), cost = 2^(2:9)))

I get following error:

Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'x' in selecting a method for function 't': error in evaluating the argument 'x' in selecting a method for function 't': Subscripts out of bound

This error depends on the label that I use (sometimes it works and sometimes in doesn’t). Do you have an idea where does this come from? I could provide an example if needed.

Thanks!

**Comment by UnixJunkie** [comment]
I don't think you are using ocaml.
You should ask the authors of the orsvm R package, of some R users mailing list, or on stackoverflow.
